### PR TITLE
Examples fix

### PR DESCRIPTION
**Pull request by CollinCunningham**
Changes made to get examples working with adafruit_ble lib in adafruit-circuitpython-bundle-5.x-mpy-20191216

### CODE REVIEW

**Comment by CollinCunningham** [comment]
Weird - unexpected-line-ending-format errors from mu editor? 
Will revisit this when I have more time.

**Comment by makermelissa** [comment]
That's due to https://github.com/adafruit/Adafruit_Blinka/issues/202

**Comment by makermelissa** [comment]
Issue should be resolved now.

**Comment by CollinCunningham** [comment]
Thanks @makermelissa - I'll loop back to this soon

**Comment by makermelissa** [comment]
Apparently this isn't quite fixed yet. I have a PR for a likely fix in though. I can update when it is verified.

**Comment by makermelissa** [comment]
Ok, now it's in a working state.

**Pull request closed without merging**
