### PR TITLE
sphinx doc improvements

### PR DESCRIPTION
**Pull request by ktdreyer**
I've updated the Sphinx documentation to fix some bad copy-and-pastes and make things clearer.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by tannewt** [comment]
Would you mind updating the issues PyLint flagged? I know they aren't from your PR but the build is failing with them.

**Comment by ktdreyer** [comment]
Sure. I'm going to push a separate PR for those.

**Comment by ktdreyer** [comment]
PyLint fix in https://github.com/adafruit/Adafruit_CircuitPython_BluefruitConnect/pull/25

**Pull request merged**
